repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.0.0  # Use the latest version of Gitleaks
    hooks:
      - id: gitleaks
        args: [--config-path=gitleaks.toml]  # Optional: specify your custom config file
        pass_filenames: false  # Prevent passing filenames to Gitleaks

