# gitleaks.toml

[[rules]]
    description = "AWS Access Key"
    regex = '''(?i)(aws_access_key_id|aws_secret_access_key)[\s]*=[\s]*([A-Z0-9]{20}|[A-Za-z0-9/+=]{40})'''
    entropy = 3.5

[[rules]]
    description = "Slack Webhook URL"
    regex = '''https:\/\/hooks\.slack\.com\/services\/T[A-Z0-9]+\/B[A-Z0-9]+\/[0-9a-zA-Z]+'''
    entropy = 3.0

